version: "3.3"

services:
  tpm:
    build: .
    container_name: tpm
    environment:
      - IPSERVER=0.0.0.0 # type here your machine network address, something like: 192.168.1.16
      - DOMAIN=myhouse.localhost
      - DNS_SERVER_PROVIDER=pihole
    volumes:
      - ${PWD}/certs:/etc/certs
      - ${PWD}/pihole/etc-pihole/:/etc/pihole/ # 05-pihole-custom-cname.conf
      - ${PWD}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/ # custom.list
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tpm.tls=true"
      - "traefik.http.routers.tpm.rule=Host(`tpm.myhouse.localhost`)"

  pihole:
    image: pihole/pihole:2024.07.0
    container_name: pihole
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    environment:
      - TZ=America/Sao_Paulo
      - WEBTHEME=default-darker
      - WEBPASSWORD=admin
    volumes:
      - ${PWD}/pihole/etc-pihole/:/etc/pihole/
      - ${PWD}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.rule=Host(`pihole.myhouse.localhost`)"

  whoami:
    image: traefik/whoami:v1.10
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.myhouse.localhost`)"

  traefik:
    image: traefik:v3.1.5
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/certs:/etc/certs:ro
      - ${PWD}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${PWD}/traefik/config.yml:/etc/traefik/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
    depends_on:
      tpm:
        condition: service_healthy
