http:
  services:
    ventoy:
      loadBalancer:
        servers:
          - url: "http://192.168.1.149:8081/"

  routers:
    traefik:
      rule: "Host(`traefik.myhouse.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "myhouse.localhost"
            sans:
              - "*.myhouse.localhost"

    ventoy:
      rule: "Host(`ventoy.myhouse.localhost`)"
      service: "ventoy"
      tls:
        domains:
          - main: "myhouse.localhost"
            sans:
              - "*.myhouse.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
